@startuml StarDocumentSequence
    autonumber
    actor "User" as user
    participant "Client (App/Web)" as client
    participant "Backend Server" as server
    database "Database" as db
    participant "File Storage Server" as fileStorage

    ' User đánh dấu tài liệu
    user -> client: Chọn tài liệu & nhấn "bookmark"
    activate client
    client -> server: POST /api/document/:id/bookmark
    activate server

    ' Nếu người dùng đã đánh dấu tài liệu trước đó, thì bỏ đánh dấu
    server -> db: Kiểm tra xem người dùng \n đã đánh dấu tài liệu chưa
    activate db
    alt Người dùng đã đánh dấu tài liệu trước đó
        db --> server: Người dùng đã đánh dấu tài liệu
        server -> db: Bỏ đánh dấu tài liệu
        db --> server: Bỏ đánh dấu thành công
        server --> client: Trả về kết quả thành công (200 OK) + thông báo
        client --> user: Hiển thị "Bỏ đánh dấu tài liệu thành công"
    else Người dùng chưa đánh dấu tài liệu
        db --> server: Người dùng chưa đánh dấu tài liệu
        server -> db: Thêm bản ghi đánh dấu tài liệu
        db --> server: Thêm thành công
        deactivate db
        server --> client: Trả về kết quả thành công + thông báo
        deactivate server
        client --> user: Hiển thị "Đánh dấu tài liệu thành công"
        deactivate client
    end 
    
    deactivate server
    deactivate client
@enduml